### ISSUE TITLE
Yarn installation step could be included in the README file

### ISSUE THREAD

**Issue by jantonioavalos** [narative/gatsby-starter-novela#10]
Before running `yarn dev`. People will need to run:
`sudo npm install -g yarn`

Or further details at [yarn](https://yarnpkg.com/getting-started/install) documentation.

Just as consideration. Thanks guys!

**Comment by brotzky** [comment]
Would be a nice first PR @jantonioavalos ❤️.
Might be easier to link to their documentation incase installation ever changes.

**Comment by jantonioavalos** [comment]
Sure I'll do it! I was intimidated since I'm new contributing out of my team at work.

**Comment by jantonioavalos** [comment]
Done. Thanks @brotzky !
