### ISSUE TITLE
Blog Name on the top can't be edited.

### ISSUE THREAD

**Issue by heytanay** [narative/gatsby-starter-novela#12]
I have cloned this repository and did some changes, but I couldn't find a way to edit the *Narrative Themes* logo at the top of the web site. I also used the inspect element, but no progress.
It would be very kind if I can be shown a way to do it.
Thank you!

![Screenshot (575)](https://user-images.githubusercontent.com/26519539/85915882-faad6a80-b868-11ea-8e67-21c911e3ba93.png)

**Comment by brotzky** [comment]
@heytanay this is how to change the Logo of your site:

https://github.com/narative/gatsby-theme-novela#adding-your-logo
