### ISSUE TITLE
Support for Pages

### ISSUE THREAD

**Issue by stephenajulu** [narative/gatsby-starter-novela#13]
Hi, how are you?

Is it possible to add pages to this and if not could you kindly add support with possible a sliding menu?

Implementation

![Screenshot_2020-08-16 TechWit v0 7](https://user-images.githubusercontent.com/42298053/90332109-dcd7c880-dfc2-11ea-8ac5-c9b781fe0438.png)

![Screenshot_2020-08-16 TechWit v0 7 2](https://user-images.githubusercontent.com/42298053/90332113-e3664000-dfc2-11ea-98d7-93f2b20ffeac.png)

By clicking the menu icon, the full menu would slide in. or something similar.

It would be great because am interested in making a multi authored tech blog using this theme with pages like a Privacy Policy, About, Terms and Conditions, Contact and more.

If you are to busy with other things, a process to do something similar would be greatly appreciated.

Also side note how can i add an image right below the logo and icons or above them?

I am not skilled dev(working towards that) and am new to JS based Static Site Generators like Gatsby and Gridsome but i am interested in learning while building this blog through instructions.

**Comment by brotzky** [comment]
If you'd like to add this feature we recommend forking. There are some other examples of others building this type of feature for themselves if you search around.
