### ISSUE TITLE
How to change logo from 'narative themes' to personal logo?

### ISSUE THREAD

**Issue by multibdoyle** [narative/gatsby-starter-novela#21]
Hello - Thank you so much for the great blog template. I see someone else already asked this but I'm a little confused because the answer references a different repo, gatsby-theme-novela, which is now archived - but which I think is still the basis for 'starter-novela'? 

Essentially I want to change the logo from the current 'narative themes' logo to my own file, which sounds like it might need to be in a 'svg' format - I'm not sure where to update that in gatsby-theme-novela, though? Any guidance is much appreciated :)
https://github.com/narative/gatsby-starter-novela/issues/6

**Comment by dexiota** [comment]
https://github.com/narative/gatsby-theme-novela#adding-your-logo
